source 'https://rubygems.org'

# gem 'ffi'
gem 'jekyll', '>= 4.3.2'
# gem 'nokogumbo', '=2.0.3'
# gem 'ptools'

group :jekyll_plugins do
  gem 'classifier-reborn'
  gem 'jekyll_video', path: '../'  # use unreleased gem dependencies defined in the parent project
  gem 'html-proofer'
  gem 'jekyll-assets', git: 'https://github.com/envygeeks/jekyll-assets'
  gem 'jekyll-environment-variables'
  gem 'jekyll-tagging'
end

group :test, :development do
  gem 'debug', '>= 1.0.0', require: false
  gem 'rspec-core', require: false
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
end
